# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: draichi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          plugin_introduction: yes

          plugin_activity: yes
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: A

          plugin_stargazers: yes

          plugin_traffic: yes
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_facts: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          
          plugin_topics: yes
